batch_size: 64
epochs: 5
validate_every_n_epochs: 1
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 100
weight_decay: 10e-6
model:
  out_dim: 128
  base_model: "scatsimclr12"
  J: 4
  L: 12

dataset:
  dataset: "cifar20"
  input_shape: (96, 96, 3)
  valid_size: 0.05

loss:
  temperature: 0.5
  use_cosine_similarity: True
